[tox]
envlist =
    py38

[pytest]
filterwarnings =
    error::DeprecationWarning
    error::PendingDeprecationWarning

[testenv]
passenv = USERNAME
commands = py.test --cov myapi {posargs} --cov-report term-missing
deps =
    pytest
    pytest-cov
