[tox]
envlist =
    py311
    py314

[pytest]
filterwarnings =
    error::DeprecationWarning
    error::PendingDeprecationWarning

[testenv]
passenv = USERNAME
commands =
    pip install --upgrade pip
    pip install -e .[test]
    py.test --cov myapi {posargs} --cov-report term-missing
